
# https://gohugo.io/overview/configuration/

baseurl = "https://parsiya.net/"
# baseurl = "http://parsiya.io/"
disablePathToLower = false
languageCode = "en-us"
title = "Parsia's Den"
theme = "hugo-octopress"

# number of blog posts displayed in each page
paginate = 6

# frontmatter will be generated in yaml format
metadataformat = "yaml"

pygmentsuseclasses = false
pygmentsstyle = "solarized_dark"

# you need to install Solarized from https://github.com/john2x/solarized-pygment.git
# Octopress blog used Solarized_dark
# options are solarized_dark (octopress), solarized_dark256 and default (solarized light)

# will make the highlight shortcode and ``` do the same thing - otherwise they are treated differently and we do not want that
pygmentscodefences = true

disqusShortname = "parsiya"

# can pass in pygments options here, it can also be added in the highlight shortcode
# pygmentsoptions = "linenos=true"

[permalinks]
post = "/blog/:year-:month-:day-:title/" # change the post URL to look like the old ones

[indexes]
  tag = "tags"
  category = "categories"

# menu
# links will open in a new window except links to "/" - links are added to navigation in hugo-octopress/layouts/partials/navigation.html
[[menu.main]]
  Name = "Blog"
  URL = "/"
  weight = -6

[[menu.main]]
  Name = "The other guy from Wham!"
  URL = "https://www.google.com/search?q=andrew+ridgeley"
  weight = -4

[[menu.main]]
  Name = "All Posts"
  URL = "/archive/"
  weight = -5

[[menu.main]]
  Name = "Cheat Sheet"
  URL = "/cheatsheet/"
  weight = -3

[[menu.main]]
  Name = "This theme on Github"
  URL = "https://github.com/parsiya/hugo-octopress"
  weight = 0

# sidebar menus
# enable with "sidebar_menu_enabled = true" in [oarams]
# header text is "sidebar_menu_header" in [params]
[[menu.sidebar]]
  Name = "Thick Client Proxying "
  URL = "/categories/thick-client-proxying/"
  weight = -1

[[menu.sidebar]]
  Name = "Burp"
  URL = "/categories/burp/"
  weight = 0

[[menu.sidebar]]
  Name = "Hipchat"
  URL = "/categories/hipchat/"
  weight = 1

[[menu.sidebar]]
  Name = "Learning Golang"
  URL = "/categories/go/"
  weight = 1.5

[[menu.sidebar]]
  Name = "Reverse Engineering"
  URL = "/categories/reverse-engineering/"
  weight = 2

[[menu.sidebar]]
  Name = "Crypto"
  URL = "/categories/crypto/"
  weight = 3

[[menu.sidebar]]
  Name = "All Posts"
  URL = "/archive/"
  weight = 4

[[menu.sidebar]]
  Name = "Migration to Hugo"
  URL = "/categories/migration-to-hugo/"
  weight = 5

[params]

  navigationNewWindow = true
  sidebarRecentLimit = 10

  sidebarHeader = "Who am I?"

  sidebarText = """I am Parsia Hakimian. Current (mostly) Senior Security Consultant at [Synopsys](https://www.synopsys.com/software-integrity.html).
  </br></br>
  I am interested in application security, reverse engineering, Python, C and computer games (not necessarily in that order).
  </br></br>
  You can contact me via email parsia.h[att]google's email or any method below.
  </br></br>
  This website should be usable without JavaScript. Only Disqus needs it and Google Analytics is now disabled. If you encounter any problems let me know.
  """

  sidebarMenuEnabled = true
  sidebarMenuHeader = "Collections"

  notfoundHeader = "There's nothing here"
  notfoundText = """You can never go back."""

  # if false, all of the post will appear on front page (and in pagination)
  truncate = true

  # author's name (this will appear in metadata and under posts)
  author = "Parsia"

  # appears in the site header under website title
  subtitle = "Because no one wants to be the other guy from Wham!"

  # used in the search engine
  searchEngineURL = "https://www.google.com/search"

  # Text of the Continue Reading label. &rarr; == right arrow, but it gets messed up in the string so we will add it to index.html manually
  continueReadingText = "Would you like to know more?"

  # Google analytics code
  # googleAnalytics = "UA-55491306-1"

  bitbucket = "https://bitbucket.org/parsiya/"
  twitter = "https://twitter.com/cryptogangsta/"
  keybase = "https://keybase.io/parsiya/"
  github = "https://github.com/parsiya/"
  linkedin = "https://www.linkedin.com/in/parsiya"

  rss = true  # switch to true to enable RSS icon link

  defaultDescription = ""

  # does this even work in action?
  defaultKeywords = ["Parsia Hakimian" , "Parsiya" , "infosec" , "information security"]

  tableOfContents = false

  # generate taxonomy list and stuff
  # generateTaxonomyList = true

# blackfriday is Hugo's markdown engine. Options are at: https://gohugo.io/overview/configuration/ (scroll down to "Configure Blackfriday rendering")
[blackfriday]
  hrefTargetBlank = true # open the external links in a new window
  fractions = false
