
# https://gohugo.io/overview/configuration/

baseurl = "https://parsiya.net/"
disablePathToLower = false
languageCode = "en-us"
title = "Parsia's Den"
theme = "Hugo-Octopress"

# number of blog posts displayed in each page
paginate = 6

# frontmatter will be generated in yaml format
metadataformat = "yaml"

# will make the highlight shortcode and ``` do the same thing - otherwise they are treated differently and we do not want that
pygmentscodefences = true

# style
pygmentsStyle = "solarized-dark"

disqusShortname = "parsiya"

# disable RSS on everything other than home
[outputs]
  section = ["HTML"]
  taxonomy = ["HTML"]
  taxonomyTerm = ["HTML"]

[permalinks]
  post = "/blog/:year-:month-:day-:title/" # change the post URL to look like the old ones

# menu
# links will open in a new window except links to "/" - links are added to navigation in hugo-octopress/layouts/partials/navigation.html
# [[menu.main]]
#   Name = "Blog"
#   URL = "/"
#   weight = 0

# [[menu.main]]
#   Name = "All Posts"
#   URL = "/"
#   weight = 1

[[menu.main]]
  Name = "About Me!"
  URL = "/about/"
  weight = 2

[[menu.main]]
  Name = "Cheat Sheet"
  URL = "/cheatsheet/"
  weight = 5

[[menu.main]]
  Name = "My Clone"
  URL = "http://parsiya.io/"
  weight = 10

[[menu.main]]
  Name = "This theme"
  URL = "https://github.com/parsiya/hugo-octopress"
  weight = 15

[[menu.main]]
  Name = "AWSome.pw"
  URL = "http://awsome.pw"
  weight = 20

[[menu.main]]
  Name = "The other guy from Wham!"
  URL = "https://www.google.com/search?q=andrew+ridgeley"
  weight = 25

# sidebar menus
# enable with "sidebar_menu_enabled = true" in [oarams]
# header text is "sidebar_menu_header" in [params]
[[menu.sidebar]]
  Name = "Thick Client Proxying"
  URL = "/categories/thick-client-proxying/"
  weight = 5

[[menu.sidebar]]
  Name = "Go/Golang"
  URL = "/categories/go/"
  weight = 10

[[menu.sidebar]]
  Name = "Blockchain/Distributed Ledgers"
  URL = "/categories/blockchain/"
  weight = 15

[[menu.sidebar]]
  Name = "WinAppDbg"
  URL = "/categories/winappdbg/"
  weight = 20

[[menu.sidebar]]
  Name = "Crypto(graphy)"
  URL = "/categories/crypto/"
  weight = 30

[[menu.sidebar]]
  Name = "Reverse Engineering"
  URL = "/categories/reverse-engineering/"
  weight = 25

[params]

  navigationNewWindow = true
  # disable recent posts section in sidebar
  sidebarRecentLimit = 0

  sidebarHeader = "Who am I?"

  sidebarText = """I am Parsia Hakimian. Senior Security Consultant at [Synopsys](https://www.synopsys.com/software-integrity.html).
  </br></br>
  This is my personal site where I document my interests such as application security, reverse engineering, Go, cryptography and computer games.
  </br></br>
  If you want to know more, click on [About Me!](/about/).
  """

  sidebarMenuEnabled = true
  sidebarMenuHeader = "Collections"

  notfoundHeader = "There's nothing here"
  notfoundText = """You can never go back."""

  # if false, all of the post will appear on front page (and in pagination)
  truncate = true

  # author's name (this will appear in metadata and under posts)
  author = "Parsia"

  # appears in the site header under website title
  subtitle = "The knowledge of anything, since all things have causes, is not acquired or complete unless it is known by its causes. - Avicenna"

  # used in the search engine
  searchEngineURL = "https://www.google.com/search"

  # Text of the Continue Reading label. &rarr; == right arrow, but it gets messed up in the string so we will add it to index.html manually
  continueReadingText = "Would you like to know more?"

  # Google analytics code
  # googleAnalytics = "UA-55491306-1"

  bitbucket = "https://bitbucket.org/parsiya/"
  twitter = "https://twitter.com/cryptogangsta/"
  keybase = "https://keybase.io/parsiya/"
  github = "https://github.com/parsiya/"
  linkedin = "https://www.linkedin.com/in/parsiya"

  rss = true  # switch to true to enable RSS icon link

  defaultDescription = ""

  # does this even work in action?
  defaultKeywords = ["Parsia Hakimian" , "Parsiya" , "infosec" , "information security"]

  tableOfContents = false

  # generate taxonomy list and stuff
  generateTaxonomyList = true

  # Twitter card config
  # Enable with this.
  twitterCardEnabled = true
  # Don't include the @.
  # twitterCardSite = 
  twitterCardDomain = "parsiya.net"
  # Don't inclue the @.
  twitterCardAuthor = "CryptoGangsta"

# blackfriday is Hugo's markdown engine. Options are at: https://gohugo.io/overview/configuration/ (scroll down to "Configure Blackfriday rendering")
[blackfriday]
  hrefTargetBlank = true # open the external links in a new window
  fractions = false
