# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo-Octopress"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Port of the Octopress classic theme for Hugo"
homepage = "http://siteforthistheme.com/"
tags = ["Octopress", "Hugo"]
features = ["blog", ""]
min_version = 0.14

[author]
  name = "Parsia Hakimian"
  homepage = "http://parsiya.net"

# If porting an existing theme
[original]
  name = "Octopress classic theme"
  homepage = "http://octopress.org"
  repo = "https://github.com/imathis/octopress/tree/master/.themes/classic"
